version: "3.9"

services:

  db:
    image: postgres
    volumes:
      - data:/home/data
    environment:
      POSTGRES_DB: road_safety
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  django:
    build: .
    command: bash -c "
        python traffic_accidents/manage.py setup_input
        && python traffic_accidents/manage.py setup_dwh
        && python traffic_accidents/manage.py migrate
        && python traffic_accidents/manage.py runserver
      "
    container_name: api.django
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  data:
    external: true