version: "3.9"

services:

  db:
    image: postgres
    container_name: traffic.db
    volumes:
      - data:/traffic_accidents/traffic/data
    environment:
      POSTGRES_DB: road_safety
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  init:
    build: .
    command: bash -c "
        python traffic_accidents/manage.py setup_input
        && python traffic_accidents/manage.py setup_dwh
        && python traffic_accidents/manage.py migrate
      "
    container_name: traffic.django
    depends_on:
      - db

  web:
    build: .
    command: bash -c "python traffic_accidents/manage.py runserver 0.0.0.0:8000"
    container_name: traffic.web
    ports:
      - 8000:8000

volumes:
  data: